### PR TITLE
chore: update lib so project can compile with 1.14 and migrate Config

### PR DESCRIPTION
**Pull request by pdgonzalez872**
- [x] I acknowledge my contribution to the website does not assert comparative or superlative differences of one product, project, company or individual over another.

# Screenshots

Compilation error:
```
==> extwitter                                                                                                                                                                                    
Compiling 25 files (.ex)                                                                                                                                                                         
                                                                                                                                                                                                 
== Compilation error in file lib/extwitter/model.ex ==                                                                                                                                           
** (ArgumentError) unknown fields [:raw_data] in :except when deriving the Inspect protocol for ExTwitter.Model.DirectMessage                                                                    
    (elixir 1.14.0) lib/inspect.ex:580: Inspect.Any.validate_option/4                                                                                                                            
    (elixir 1.14.0) expanding macro: Inspect.Any.__deriving__/3                                                                                                                                  
    lib/extwitter/model.ex:136: ExTwitter.Model.DirectMessage (module)                                                                                                                           
could not compile dependency :extwitter, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile extwitter", update it with "mix deps.u
pdate extwitter" or clean it with "mix deps.clean extwitter"  
```

The above was fixed in the latest release of `extwitter`.

`Config` warnings:

```
warning: use Mix.Config is deprecated. Use the Config module instead                                                                                                                             
  config/dev.exs:1   
```

Hope this helps!

### CODE REVIEW

**Comment by starbelly** [comment]
Thank you @ pdgonzalez872  ❤️

**Comment by pdgonzalez872** [comment]
You got it! Thanks for your involvement with the erlef @starbelly :heart:
